name: CI
on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}